const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=Array.from({length:13},(_,i)=>fs.readFileSync('game-v9-part'+String(i).padStart(2,'0')+'.txt','utf8')).join('');
let script=html.match(/<script>([\s\S]*)<\/script>/)[1];
script=script.replace('})();','globalThis.test={start,update,seed,makeFood,visibleAirTarget,edible,get:()=>({player,foods,enemies,ufos,planes,lasers,cam,grounds,boats,level,score,paused,WORLD}),ready:()=>{cityReady=true;ferryReady=true;sydneyReady=true;groundArtLoaded=4;},pause:togglePause,setGround:g=>{grounds=g;},setTargets:(u,p)=>{ufos=u;planes=p;foods=[];healthDrops=[];enemies=[];grounds=[];boats=[];}};})();');
const nodes=new Map(),ctx=new Proxy({getImageData:()=>({data:new Uint8ClampedArray(0)}),createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});
function node(){return {style:{},hidden:false,getContext:()=>ctx,addEventListener(){},setAttribute(){}}}
const env={console,innerWidth:390,innerHeight:844,devicePixelRatio:1,localStorage:{getItem:()=>0},document:{querySelector:()=>node(),getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},createElement:node,addEventListener(){}},Image:class {complete=false;set src(s){this.naturalWidth=1024;this.naturalHeight=3072;}},addEventListener(){},requestAnimationFrame(){}};
vm.createContext(env);vm.runInContext(script,env);const t=env.test;t.start();let s=t.get();assert(!nodes.get('overlay').hidden===false);assert(s.enemies.every(e=>e.kind!=='ptero'));assert(s.foods.every(f=>f.type!=='fish'));assert(s.foods.length===55);assert(s.foods.every((f,i)=>s.foods.every((g,j)=>i===j||Math.hypot(f.x-g.x,f.y-g.y)>=150)));
s.player.stage=6;s.player.x=195;s.player.y=400;s.cam.x=0;s.cam.y=0;
const off={kind:'ufo',x:450,y:400,size:82,hp:2,vx:0,phase:0};t.setTargets([off],[]);t.update(0);assert(off.hp===2,'Offscreen UFO must not be shot');
const plane={kind:'plane',x:300,y:400,size:118,hp:2,vx:0,phase:0};t.setTargets([], [plane]);t.update(0);assert(plane.hp===1,'Visible plane should be shot');s.player.laser=0;t.update(0);assert(t.get().planes.length===0,'Destroyed plane stays cleared');
assert(t.edible({kind:'crow'}));s.player.stage=0;assert(!t.edible({kind:'crow'}));
for(const kind of ['gorilla','alligator','raccoon','rat','kangaroo','koala']){s.player.stage=6;s.player.x=195;s.player.y=900;t.setTargets([off],[]);t.setGround([{kind,x:195,y:900,origin:195,roam:140,vx:0,size:120}]);const hp=s.player.hp;t.update(0);assert(t.get().grounds.length===0);assert(s.player.hp===hp,'Mech eats shore enemies without damage');}
const cityLayout=state=>{const bottoms=state.grounds.map(g=>state.WORLD.h-(g.y+g.size/2)),xs=state.grounds.map(g=>g.x).sort((a,b)=>a-b);assert(state.grounds.length===8,'City stages use eight ground animals');assert(Math.max(...bottoms)-Math.min(...bottoms)>90,'Animals use staggered sidewalk depths');assert(bottoms.every(y=>y>=36&&y<=172),'Animals stay on the sidewalk');assert(xs.slice(1).every((x,i)=>x-xs[i]>400),'Animals begin well spaced');assert(state.grounds.every(g=>g.roam<=80),'Animals cannot roam far enough to bunch together');};
const score=t.get().score;t.ready();t.setTargets([],[]);t.update(0);assert(t.get().level===1);assert(s.player.stage===0&&s.player.xp===0&&s.player.hp===100);assert(t.get().score===score);assert(t.get().grounds.every(g=>['raccoon','rat'].includes(g.kind)&&g.size>100)&&t.get().planes.length===4);cityLayout(t.get());s=t.get();s.player.stage=6;t.setTargets([],[]);t.update(0);assert(t.get().level===2);assert(t.get().grounds.every(g=>['kangaroo','koala'].includes(g.kind)));cityLayout(t.get());assert(t.get().boats.length===0,'Sydney must not contain boats');assert(/walkFps=g.kind==='raccoon'\|\|g.kind==='rat'\?3\.2:5/.test(script));t.start();assert(t.get().level===0);console.log('PASS: slower Hudson walk cycles, eight spaced city animals, staggered sidewalk depth, and no Sydney boats.');
